### ISSUE TITLE
Crashed in the background on Android 12

### ISSUE THREAD

**Issue by rugk** [slp/android-smarterwifi#1]
## STR

I was just using it in a known location, WiFi enabled and connected. (Besides that I did not check whether the app actually works on Android 12 anyway)

## Logcat

```
FATAL EXCEPTION: main
Process: net.kismetwireless.android.smarterwifimanager, PID: 15731
java.lang.RuntimeException: Unable to stop service net.kismetwireless.android.smarterwifimanager.services.SmarterWifiService@e4cbbd3: java.lang.IllegalArgumentException: Receiver not registered: null
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4689)
	at android.app.ActivityThread.access$2100(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2096)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: null
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1555)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1789)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:769)
	at net.kismetwireless.android.smarterwifimanager.services.SmarterWifiService.onDestroy(SmarterWifiService.java:454)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4669)
	... 9 more
```

## System

Device: Pixel 4
OS: Android 12, CalyxOS 3.2.0
source: F-Droid
version: v2016.12.85

Build ID: `SQ1D.220205.003.223`
Package: et.net.kismetwireless.android.smarterwifimanager (as I don't know whether this is the correct repo as F-Droid has no metadata linked)

**Comment by rugk** [comment]
Hmm found a (different) github handle for the creator, pinging to let them know: @kismetwireless
